# Generated by Django 5.1.4 on 2026-02-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '接口分類',
                'verbose_name_plural': '接口分類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='變量名')),
                ('value', models.TextField(verbose_name='變量值')),
                ('var_type', models.CharField(choices=[('string', '字符串'), ('token', 'Token'), ('json', 'JSON')], default='string', max_length=20, verbose_name='類型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '全局變量',
                'verbose_name_plural': '全局變量',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='報告名稱')),
                ('status', models.CharField(choices=[('running', '執行中'), ('completed', '已完成'), ('error', '執行錯誤')], default='running', max_length=20, verbose_name='狀態')),
                ('total', models.IntegerField(default=0, verbose_name='總數')),
                ('passed', models.IntegerField(default=0, verbose_name='通過')),
                ('failed', models.IntegerField(default=0, verbose_name='失敗')),
                ('error', models.IntegerField(default=0, verbose_name='錯誤')),
                ('duration', models.FloatField(default=0.0, verbose_name='耗時(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '測試報告',
                'verbose_name_plural': '測試報告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名稱')),
                ('url', models.TextField(verbose_name='請求URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='請求方式')),
                ('content_type', models.CharField(choices=[('json', 'application/json'), ('form', 'application/x-www-form-urlencoded'), ('multipart', 'multipart/form-data')], default='json', max_length=20, verbose_name='請求類型')),
                ('headers', models.TextField(default='{}', verbose_name='請求頭 (JSON)')),
                ('params', models.TextField(default='{}', verbose_name='Query參數 (JSON)')),
                ('body', models.TextField(default='{}', verbose_name='請求體 (JSON)')),
                ('extract_vars', models.TextField(default='[]', verbose_name='提取變量規則 (JSON)')),
                ('encrypted', models.BooleanField(default=False, verbose_name='啟用加密')),
                ('encryption_key', models.CharField(blank=True, default='', max_length=200, verbose_name='加密密鑰')),
                ('encryption_algorithm', models.CharField(choices=[('AES', 'AES'), ('BASE64', 'BASE64'), ('MD5', 'MD5')], default='AES', max_length=20, verbose_name='加密算法')),
                ('assertions', models.TextField(default='[]', verbose_name='斷言規則 (JSON)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, default='', verbose_name='接口描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.category', verbose_name='所屬分類')),
            ],
            options={
                'verbose_name': '接口配置',
                'verbose_name_plural': '接口配置',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=200, verbose_name='接口名稱')),
                ('url', models.TextField(verbose_name='請求URL')),
                ('method', models.CharField(max_length=10, verbose_name='請求方式')),
                ('request_headers', models.TextField(default='{}', verbose_name='實際請求頭')),
                ('request_params', models.TextField(default='{}', verbose_name='請求參數')),
                ('request_body', models.TextField(default='{}', verbose_name='請求體')),
                ('response_status', models.IntegerField(default=0, verbose_name='響應狀態碼')),
                ('response_headers', models.TextField(default='{}', verbose_name='響應頭')),
                ('response_body', models.TextField(default='', verbose_name='響應體')),
                ('response_time', models.FloatField(default=0.0, verbose_name='響應時間(ms)')),
                ('status', models.CharField(choices=[('pass', '通過'), ('fail', '失敗'), ('error', '錯誤')], max_length=20, verbose_name='測試狀態')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='錯誤信息')),
                ('extracted_vars', models.TextField(default='{}', verbose_name='提取的變量')),
                ('assertion_results', models.TextField(default='[]', verbose_name='斷言結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.apiconfig', verbose_name='接口配置')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testreport', verbose_name='所屬報告')),
            ],
            options={
                'verbose_name': '測試結果',
                'verbose_name_plural': '測試結果',
                'ordering': ['created_at'],
            },
        ),
    ]
