# Generated by Django 5.1.4 on 2026-02-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名稱')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='主機')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用戶名')),
                ('password', models.CharField(max_length=200, verbose_name='密碼')),
                ('database', models.CharField(max_length=100, verbose_name='數據庫名')),
                ('charset', models.CharField(default='utf8mb4', max_length=20, verbose_name='字符集')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '數據庫配置',
                'verbose_name_plural': '數據庫配置',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='db_assertions',
            field=models.TextField(default='[]', verbose_name='數據庫斷言規則 (JSON)'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='post_sql',
            field=models.TextField(blank=True, default='', verbose_name='後置SQL（請求後執行）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='pre_sql',
            field=models.TextField(blank=True, default='', verbose_name='前置SQL（請求前執行）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='timeout',
            field=models.IntegerField(default=30, verbose_name='超時秒數'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='use_async',
            field=models.BooleanField(default=False, verbose_name='使用異步請求(httpx)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='db_assertion_results',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='post_sql_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testresult',
            name='pre_sql_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testresult',
            name='use_async',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='assertions',
            field=models.TextField(default='[]', verbose_name='HTTP斷言規則 (JSON)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.apiconfig'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='api_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='assertion_results',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='extracted_vars',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testreport'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request_body',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request_headers',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request_params',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='response_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='response_headers',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='response_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('pass', '通過'), ('fail', '失敗'), ('error', '錯誤')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='url',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='post_sql_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_sql_apis', to='core.databaseconfig', verbose_name='後置SQL數據庫'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='pre_sql_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_sql_apis', to='core.databaseconfig', verbose_name='前置SQL數據庫'),
        ),
    ]
