# Generated by Django 5.1.4 on 2026-02-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_databaseconfig_apiconfig_db_assertions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默認郵件配置', max_length=100, verbose_name='配置名稱')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='SMTP 主機')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTP 端口')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用TLS(STARTTLS)')),
                ('username', models.CharField(max_length=200, verbose_name='郵箱賬號')),
                ('password', models.CharField(max_length=200, verbose_name='郵箱密碼/授權碼')),
                ('from_addr', models.CharField(max_length=200, verbose_name='發件人地址')),
                ('from_name', models.CharField(default='API測試平台', max_length=100, verbose_name='發件人名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '郵件配置',
                'verbose_name_plural': '郵件配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RedisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名稱')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='主機')),
                ('port', models.IntegerField(default=6379, verbose_name='端口')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密碼')),
                ('db', models.IntegerField(default=0, verbose_name='DB 索引 (0-15)')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Redis 配置',
                'verbose_name_plural': 'Redis 配置',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('api_ids', models.TextField(default='[]', verbose_name='接口ID列表 (JSON)')),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron 表達式'), ('interval', '固定間隔')], default='cron', max_length=20, verbose_name='觸發方式')),
                ('cron_expr', models.CharField(blank=True, default='0 9 * * *', max_length=100, verbose_name='Cron 表達式')),
                ('interval_secs', models.IntegerField(default=3600, verbose_name='間隔秒數')),
                ('report_name_tpl', models.CharField(default='定時任務-{task}', max_length=200, verbose_name='報告名稱模板')),
                ('send_email', models.BooleanField(default=False, verbose_name='執行後發送郵件')),
                ('email_to', models.TextField(blank=True, default='', verbose_name='收件人(多個逗號分隔)')),
                ('status', models.CharField(choices=[('active', '運行中'), ('paused', '已暫停'), ('stopped', '已停止')], default='active', max_length=20, verbose_name='狀態')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次執行時間')),
                ('last_report_id', models.IntegerField(blank=True, null=True, verbose_name='上次報告ID')),
                ('last_result', models.CharField(blank=True, default='', max_length=200, verbose_name='上次結果摘要')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '定時任務',
                'verbose_name_plural': '定時任務',
                'ordering': ['-created_at'],
            },
        ),
    ]
