# Generated by Django 5.1.4 on 2026-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailconfig_redisconfig_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='body_type',
            field=models.CharField(choices=[('json', 'JSON'), ('form', 'Form表單'), ('raw', 'Raw'), ('files', '文件上傳')], default='json', max_length=20, verbose_name='Body類型'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='deepdiff_assertions',
            field=models.TextField(default='[]', verbose_name='DeepDiff斷言規則 (JSON)'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='use_session',
            field=models.BooleanField(default=False, verbose_name='使用Session保持會話'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='deepdiff_results',
            field=models.TextField(default='[]'),
        ),
    ]
