# Generated by Django 5.1.4 on 2026-03-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apiconfig_sql_extract_vars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '接口配置', 'verbose_name_plural': '接口配置'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '接口分類', 'verbose_name_plural': '接口分類'},
        ),
        migrations.AlterModelOptions(
            name='databaseconfig',
            options={'ordering': ['name'], 'verbose_name': '數據庫配置', 'verbose_name_plural': '數據庫配置'},
        ),
        migrations.AlterModelOptions(
            name='dynamicvar',
            options={'ordering': ['name'], 'verbose_name': '動態變量', 'verbose_name_plural': '動態變量'},
        ),
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': '郵件配置', 'verbose_name_plural': '郵件配置'},
        ),
        migrations.AlterModelOptions(
            name='globalvariable',
            options={'ordering': ['-updated_at'], 'verbose_name': '全局變量', 'verbose_name_plural': '全局變量'},
        ),
        migrations.AlterModelOptions(
            name='redisconfig',
            options={'ordering': ['name'], 'verbose_name': 'Redis 配置', 'verbose_name_plural': 'Redis 配置'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['-created_at'], 'verbose_name': '定時任務', 'verbose_name_plural': '定時任務'},
        ),
        migrations.AlterModelOptions(
            name='testreport',
            options={'ordering': ['-created_at'], 'verbose_name': '測試報告', 'verbose_name_plural': '測試報告'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['repeat_index', 'created_at'], 'verbose_name': '測試結果', 'verbose_name_plural': '測試結果'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用戶資料', 'verbose_name_plural': '用戶資料'},
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='allow_redirects',
            field=models.BooleanField(default=True, verbose_name='允許自動重定向 (allow_redirects)'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='cookie',
            field=models.TextField(blank=True, default='', verbose_name='Cookie (key=value; key2=value2)'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='encryption_wrapper_key',
            field=models.CharField(blank=True, default='encrypted', max_length=100, verbose_name='全局加密JSON包裝鍵名（如 data、param、encrypted）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_allow_redirects',
            field=models.BooleanField(default=True, verbose_name='OAuth2 請求允許重定向'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_base_url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='OAuth2 Base URL（如 https://auth.example.com）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_client_id',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='OAuth2 Client ID'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_client_secret',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='OAuth2 Client Secret'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_extra_params',
            field=models.TextField(blank=True, default='{}', verbose_name='[舊] OAuth2 額外參數 (JSON)'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='OAuth2 登錄密碼'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_redirect_uri',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='OAuth2 Redirect URI'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_scope',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='OAuth2 Scope（空格分隔）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_token_url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='[舊] OAuth2 Token URL'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='OAuth2 登錄用戶名'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='oauth2_verify',
            field=models.BooleanField(default=False, verbose_name='OAuth2 SSL 驗證（False=跳過自簽名憑證）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='request_verify',
            field=models.TextField(blank=True, default='', verbose_name='requests verify 參數（空=默認True, false=跳過, 或CA路徑）'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='use_oauth2',
            field=models.BooleanField(default=False, verbose_name='啟用 OAuth2 認證'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='repeat_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='response_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='body_type',
            field=models.CharField(choices=[('json', 'JSON (json=)'), ('data', 'Data (data=)'), ('params', 'Params (params=)'), ('form', 'Form (form-urlencoded)'), ('text', 'Text/Plain'), ('raw', 'Raw'), ('files', '文件上傳')], default='json', max_length=20, verbose_name='Body類型'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.category', verbose_name='所屬分類'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='content_type',
            field=models.CharField(choices=[('json', 'application/json'), ('form', 'application/x-www-form-urlencoded'), ('multipart', 'multipart/form-data')], default='json', max_length=20, verbose_name='請求類型'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='post_sql_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_sql_apis', to='core.databaseconfig', verbose_name='後置SQL數據庫'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='pre_sql_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_sql_apis', to='core.databaseconfig', verbose_name='前置SQL數據庫'),
        ),
        migrations.AlterField(
            model_name='dynamicvar',
            name='dyn_type',
            field=models.CharField(choices=[('phone', '🇨🇳 隨機中國手機號'), ('timestamp', '⏱ 當前時間戳（秒）'), ('timestamp_ms', '⏱ 當前時間戳（毫秒）'), ('datetime', '📅 當前日期時間（yyyy-MM-dd HH:mm:ss）'), ('date', '📅 當前日期（yyyy-MM-dd）'), ('uuid', '🔑 隨機 UUID')], default='phone', max_length=30, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='var_type',
            field=models.CharField(choices=[('string', '字符串'), ('token', 'Token'), ('json', 'JSON')], default='string', max_length=20, verbose_name='類型'),
        ),
    ]
