# Generated by Django 5.1.4 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apiconfig_body_type_apiconfig_deepdiff_assertions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='body_enc_rules',
            field=models.TextField(blank=True, default='[]', verbose_name='Body字段加密規則(JSON)'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='encryption_algorithm',
            field=models.CharField(choices=[('AES', 'AES-CBC'), ('AES-GCM', 'AES-GCM'), ('BASE64', 'BASE64'), ('MD5', 'MD5')], default='AES', max_length=20, verbose_name='加密算法'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='encryption_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='加密密鑰(raw)'),
        ),
    ]
