# Generated by Django 5.1.4 on 2026-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apiconfig_body_enc_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='body',
            field=models.TextField(default='{}', verbose_name='請求體 json= (JSON)'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='body_type',
            field=models.CharField(choices=[('json', 'JSON (json=)'), ('data', 'Data (data=)'), ('params', 'Params (params=)'), ('form', 'Form (form-urlencoded)'), ('text', 'Text/Plain'), ('raw', 'Raw'), ('files', '文件上傳')], default='json', max_length=20, verbose_name='Body類型'),
        ),
    ]
