# Generated by Django 5.1.4 on 2026-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_apiconfig_body_alter_apiconfig_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='pre_redis_rules',
            field=models.TextField(blank=True, default='[]', verbose_name='前置Redis取值規則(JSON)'),
        ),
    ]
