# Generated by Django 5.1.4 on 2026-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apiconfig_pre_redis_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='變量名（{{name}}）')),
                ('dyn_type', models.CharField(choices=[('phone', '🇨🇳 隨機中國手機號'), ('timestamp', '⏱ 當前時間戳（秒）'), ('timestamp_ms', '⏱ 當前時間戳（毫秒）'), ('datetime', '📅 當前日期時間（yyyy-MM-dd HH:mm:ss）'), ('date', '📅 當前日期（yyyy-MM-dd）'), ('uuid', '🔑 隨機 UUID')], default='phone', max_length=30, verbose_name='類型')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用（每次請求前生成）')),
                ('description', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '動態變量',
                'verbose_name_plural': '動態變量',
                'ordering': ['name'],
            },
        ),
    ]
