# Generated by Django 5.1.4 on 2026-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='ssl_cert',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='自定義 CA 證書路徑'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='ssl_verify',
            field=models.CharField(choices=[('true', '驗證 SSL 證書（默認）'), ('false', '跳過 SSL 驗證（忽略自簽名/內網證書）'), ('custom', '使用自定義 CA 證書')], default='true', max_length=10, verbose_name='SSL 驗證模式'),
        ),
    ]
