# Generated by Django 5.1.4 on 2026-02-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_apiconfig_ssl_cert_apiconfig_ssl_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '接口配置', 'verbose_name_plural': '接口配置'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '接口分類', 'verbose_name_plural': '接口分類'},
        ),
        migrations.AlterModelOptions(
            name='globalvariable',
            options={'ordering': ['-updated_at'], 'verbose_name': '全局變量', 'verbose_name_plural': '全局變量'},
        ),
        migrations.AlterModelOptions(
            name='testreport',
            options={'ordering': ['-created_at'], 'verbose_name': '測試報告', 'verbose_name_plural': '測試報告'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['created_at'], 'verbose_name': '測試結果', 'verbose_name_plural': '測試結果'},
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.category', verbose_name='所屬分類'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='content_type',
            field=models.CharField(choices=[('json', 'application/json'), ('form', 'application/x-www-form-urlencoded'), ('multipart', 'multipart/form-data')], default='json', max_length=20, verbose_name='請求類型'),
        ),
        migrations.AlterField(
            model_name='globalvariable',
            name='var_type',
            field=models.CharField(choices=[('string', '字符串'), ('token', 'Token'), ('json', 'JSON')], default='string', max_length=20, verbose_name='類型'),
        ),
    ]
