from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理員'), ('normal', '普通用戶')], default='normal', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={'verbose_name': '分類', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='變量名')),
                ('value', models.TextField(verbose_name='變量值')),
                ('var_type', models.CharField(choices=[('string', '字符串'), ('number', '數字'), ('boolean', '布爾'), ('json', 'JSON')], default='string', max_length=20, verbose_name='類型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': '全局變量', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='DynamicVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='變量名（{{name}}）')),
                ('dyn_type', models.CharField(choices=[('phone', '🇨🇳 隨機中國手機號'), ('timestamp', '⏱ 當前時間戳（秒）'), ('timestamp_ms', '⏱ 當前時間戳（毫秒）'), ('datetime', '📅 當前日期時間'), ('date', '📅 當前日期'), ('uuid', '🔑 隨機 UUID')], default='phone', max_length=30, verbose_name='類型')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用（每次請求前生成）')),
                ('description', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name': '動態變量', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名稱')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='主機')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用戶名')),
                ('password', models.CharField(max_length=200, verbose_name='密碼')),
                ('database', models.CharField(max_length=100, verbose_name='數據庫名')),
                ('charset', models.CharField(default='utf8mb4', max_length=20, verbose_name='字符集')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': '數據庫配置', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='RedisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名稱')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='主機')),
                ('port', models.IntegerField(default=6379, verbose_name='端口')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密碼')),
                ('db', models.IntegerField(default=0, verbose_name='DB 索引 (0-15)')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': 'Redis 配置', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默認郵件配置', max_length=100, verbose_name='配置名稱')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='SMTP 主機')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTP 端口')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用TLS(STARTTLS)')),
                ('username', models.CharField(max_length=200, verbose_name='郵箱賬號')),
                ('password', models.CharField(max_length=200, verbose_name='郵箱密碼/授權碼')),
                ('from_addr', models.CharField(max_length=200, verbose_name='發件人地址')),
                ('from_name', models.CharField(default='API測試平台', max_length=100, verbose_name='發件人名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': '郵件配置', 'ordering': ['-is_active', '-updated_at']},
        ),
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名稱')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.category', verbose_name='分類')),
                ('url', models.TextField(verbose_name='請求URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='請求方式')),
                ('content_type', models.CharField(choices=[('json', 'JSON'), ('form', 'Form'), ('raw', 'Raw'), ('files', 'Files')], default='json', max_length=20, verbose_name='請求類型')),
                ('headers', models.TextField(default='{}', verbose_name='請求頭 (JSON)')),
                ('params', models.TextField(default='{}', verbose_name='Query參數 (JSON)')),
                ('body', models.TextField(default='{}', verbose_name='請求體 json= (JSON)')),
                ('use_async', models.BooleanField(default=False, verbose_name='使用異步請求(httpx)')),
                ('timeout', models.IntegerField(default=30, verbose_name='超時秒數')),
                ('ssl_verify', models.CharField(choices=[('true', '驗證 SSL 證書（默認）'), ('false', '跳過 SSL 驗證（忽略自簽名/內網證書）'), ('custom', '使用自定義 CA 證書')], default='true', max_length=10, verbose_name='SSL 驗證模式')),
                ('ssl_cert', models.CharField(blank=True, default='', max_length=500, verbose_name='自定義 CA 證書路徑')),
                ('client_cert_enabled', models.BooleanField(default=False, verbose_name='啟用客戶端證書 (mTLS)')),
                ('client_cert', models.CharField(blank=True, default='', max_length=500, verbose_name='客戶端證書路徑 (.pem/.crt)')),
                ('client_key', models.CharField(blank=True, default='', max_length=500, verbose_name='客戶端私鑰路徑 (.pem/.key)')),
                ('extract_vars', models.TextField(default='[]', verbose_name='提取變量規則 (JSON)')),
                ('encrypted', models.BooleanField(default=False, verbose_name='啟用加密')),
                ('encryption_key', models.CharField(blank=True, default='', max_length=200, verbose_name='加密密鑰(raw)')),
                ('encryption_algorithm', models.CharField(choices=[('AES', 'AES-CBC'), ('AES-GCM', 'AES-GCM'), ('BASE64', 'BASE64'), ('MD5', 'MD5')], default='AES', max_length=20, verbose_name='加密算法')),
                ('body_enc_rules', models.TextField(blank=True, default='[]', verbose_name='Body字段加密規則(JSON)')),
                ('assertions', models.TextField(default='[]', verbose_name='HTTP斷言規則 (JSON)')),
                ('db_assertions', models.TextField(default='[]', verbose_name='數據庫斷言規則 (JSON)')),
                ('deepdiff_assertions', models.TextField(default='[]', verbose_name='DeepDiff斷言規則 (JSON)')),
                ('pre_redis_rules', models.TextField(blank=True, default='[]', verbose_name='前置Redis取值規則(JSON)')),
                ('pre_sql_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_apis', to='core.databaseconfig', verbose_name='前置SQL數據庫')),
                ('pre_sql', models.TextField(blank=True, default='', verbose_name='前置SQL（請求前執行）')),
                ('post_sql_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_apis', to='core.databaseconfig', verbose_name='後置SQL數據庫')),
                ('post_sql', models.TextField(blank=True, default='', verbose_name='後置SQL（請求後執行）')),
                ('use_session', models.BooleanField(default=False, verbose_name='使用Session保持會話')),
                ('body_type', models.CharField(choices=[('json', 'JSON Body'), ('data', 'Data (raw string/dict)'), ('params', 'Query Params (合併到URL)'), ('form', 'Form (application/x-www-form-urlencoded)'), ('text', 'Text (text/plain)'), ('raw', 'Raw (application/json string)'), ('files', 'Files (multipart/form-data)')], default='json', max_length=20, verbose_name='Body 類型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, default='', verbose_name='接口描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': 'API配置', 'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='報告名稱')),
                ('status', models.CharField(choices=[('running', '執行中'), ('completed', '已完成'), ('error', '執行錯誤')], default='running', max_length=20, verbose_name='狀態')),
                ('total', models.IntegerField(default=0, verbose_name='總數')),
                ('passed', models.IntegerField(default=0, verbose_name='通過')),
                ('failed', models.IntegerField(default=0, verbose_name='失敗')),
                ('error', models.IntegerField(default=0, verbose_name='錯誤')),
                ('duration', models.FloatField(default=0.0, verbose_name='耗時(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={'verbose_name': '測試報告', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testreport')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.apiconfig')),
                ('api_name', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('use_async', models.BooleanField(default=False)),
                ('request_headers', models.TextField(default='{}')),
                ('request_params', models.TextField(default='{}')),
                ('request_body', models.TextField(default='{}')),
                ('response_status', models.IntegerField(default=0)),
                ('response_headers', models.TextField(default='{}')),
                ('response_body', models.TextField(default='')),
                ('response_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pass', '通過'), ('fail', '失敗'), ('error', '錯誤')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_vars', models.TextField(default='{}')),
                ('assertion_results', models.TextField(default='[]')),
                ('db_assertion_results', models.TextField(default='[]')),
                ('deepdiff_results', models.TextField(default='[]')),
                ('pre_sql_result', models.TextField(default='')),
                ('post_sql_result', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name': '測試結果', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('api_ids', models.TextField(default='[]', verbose_name='接口ID列表 (JSON)')),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron 表達式'), ('interval', '固定間隔')], default='cron', max_length=20, verbose_name='觸發方式')),
                ('cron_expr', models.CharField(blank=True, default='0 9 * * *', max_length=100, verbose_name='Cron 表達式')),
                ('interval_secs', models.IntegerField(default=3600, verbose_name='間隔秒數')),
                ('report_name_tpl', models.CharField(default='定時任務-{task}', max_length=200, verbose_name='報告名稱模板')),
                ('send_email', models.BooleanField(default=False, verbose_name='執行後發送郵件')),
                ('email_to', models.TextField(blank=True, default='', verbose_name='收件人(多個逗號分隔)')),
                ('status', models.CharField(choices=[('active', '運行中'), ('paused', '已暫停'), ('stopped', '已停止')], default='active', max_length=20, verbose_name='狀態')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次執行時間')),
                ('last_report_id', models.IntegerField(blank=True, null=True, verbose_name='上次報告ID')),
                ('last_result', models.CharField(blank=True, default='', max_length=200, verbose_name='上次結果摘要')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={'verbose_name': '定時任務', 'ordering': ['-created_at']},
        ),
    ]
